// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { Article } from "../schema.js";

export const articles: Article[] = [
  {
    _createdAt: "2023-10-25T14:28:07Z",
    _id: "b7915288-c1a2-402b-8182-0cb6e94e1487",
    _rev: "Ff4ErUr0mXqJ0p2ePBUP99",
    _type: "article",
    _updatedAt: "2023-10-25T14:32:48Z",
    contents: "Widget article",
    language: "en",
    slug: {
      _type: "slug",
      current: "widget",
    },
    title: "Widget",
    translationOf: null,
  },
  {
    _createdAt: "2023-10-24T13:54:03Z",
    _id: "cf35377e-2ce2-4ae7-bb28-7c5c6e9d1883",
    _rev: "904mL5SdWNgHGZgJPr9X5z",
    _type: "article",
    _updatedAt: "2023-10-25T17:12:37Z",
    browser: {
      _ref: "07a00872-21f9-4a4d-81d4-51d42cf2491f",
      _type: "reference",
    },
    contents:
      "This is a test!\n\n# Heading\n\n<Callout>\nOh dang! Is this a React component in the middle of our content? 😱\n</Callout>\n\nTest",
    excerpt: "Summary of the page",
    language: "en",
    oses: [
      {
        _key: "6e77a87705bc",
        _ref: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
        _type: "reference",
      },
      {
        _key: "f36ad7af4deb",
        _ref: "27cf9d5b-7cb9-4555-9cee-54b2ee4847fc",
        _type: "reference",
      },
    ],
    slug: {
      _type: "slug",
      current: "how-to-update-opera-on-windows",
    },
    title: "How to Update Opera on Windows",
    translationOf: {
      _ref: "cf35377e-2ce2-4ae7-bb28-7c5c6e9d1883",
      _type: "reference",
    },
  },
  {
    _createdAt: "2023-10-24T13:54:03Z",
    _id: "dad06709-cba4-4919-8279-fab5596554c2",
    _rev: "904mL5SdWNgHGZgJPr1YEX",
    _type: "article",
    _updatedAt: "2023-10-25T15:45:51Z",
    browser: {
      _ref: "07a00872-21f9-4a4d-81d4-51d42cf2491f",
      _type: "reference",
    },
    contents: "This is a test",
    language: "id",
    oses: [
      {
        _key: "b97c2bb45ad5",
        _ref: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
        _type: "reference",
      },
    ],
    slug: {
      _type: "slug",
      current: "cara-memperbarui-opera-di-windows",
    },
    title: "Cara Memperbarui Opera di Windows",
    translationOf: {
      _ref: "cf35377e-2ce2-4ae7-bb28-7c5c6e9d1883",
      _type: "reference",
    },
  },
];
