// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { Feature } from "../schema.js";

export const features: Feature[] = [
  {
    _createdAt: "2023-11-13T10:35:40Z",
    _id: "30d67e62-0f8c-4648-ab91-dfca41410412",
    _rev: "6tBtT7HSXJBZgGx8QinYlH",
    _type: "feature",
    _updatedAt: "2023-11-13T10:35:40Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Plugins support",
      },
    ],
    slug: {
      _type: "slug",
      current: "plugins-support",
    },
  },
  {
    _createdAt: "2023-11-12T10:59:32Z",
    _id: "3c42fbee-fa58-4c34-82b4-07324a097635",
    _rev: "P8iX8yLNzdMX2eS89dc8G5",
    _type: "feature",
    _updatedAt: "2023-11-13T10:31:05Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    description: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Blocks ads from appearing on websites",
      },
    ],
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block ads",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-ads",
    },
  },
  {
    _createdAt: "2023-11-13T10:34:48Z",
    _id: "4a4fce62-dc7d-40d9-b1a5-84e6a92366e2",
    _rev: "P8iX8yLNzdMX2eS89dcWZR",
    _type: "feature",
    _updatedAt: "2023-11-13T10:34:48Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Private browsing",
      },
    ],
    slug: {
      _type: "slug",
      current: "private-browsing",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:28Z",
    _id: "a32cbcd7-c281-45f5-9041-a6d2e1e26767",
    _rev: "g4WGtXEJHMGyIQGoBriHPr",
    _type: "feature",
    _updatedAt: "2023-11-13T10:33:28Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Password manager",
      },
    ],
    slug: {
      _type: "slug",
      current: "password-manager",
    },
  },
  {
    _createdAt: "2023-11-13T23:34:38Z",
    _id: "bb5f2721-c9ca-4421-a8ba-d6cd023e7617",
    _rev: "6tBtT7HSXJBZgGx8Qo7DNN",
    _type: "feature",
    _updatedAt: "2023-11-13T23:34:38Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Picture-in-Picture",
      },
    ],
    slug: {
      _type: "slug",
      current: "picture-in-picture",
    },
  },
  {
    _createdAt: "2023-11-13T10:36:23Z",
    _id: "bd5e7853-c514-4498-9b92-82ec06c78122",
    _rev: "6tBtT7HSXJBZgGx8QinnP7",
    _type: "feature",
    _updatedAt: "2023-11-13T10:36:23Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Chrome web store support",
      },
    ],
    slug: {
      _type: "slug",
      current: "chrome-web-store-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:35:21Z",
    _id: "e5ec9ff5-d466-4d4c-976c-48b3bf104e3f",
    _rev: "6tBtT7HSXJBZgGx8QioMoL",
    _type: "feature",
    _updatedAt: "2023-11-13T10:38:11Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Firefox add-ons support",
      },
    ],
    slug: {
      _type: "slug",
      current: "firefox-add-ons-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:04Z",
    _id: "f90318ae-0fb2-487c-a384-bc3cfb534c57",
    _rev: "P8iX8yLNzdMX2eS89dcNAc",
    _type: "feature",
    _updatedAt: "2023-11-13T10:33:04Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Cloud sync",
      },
    ],
    slug: {
      _type: "slug",
      current: "cloud-sync",
    },
  },
  {
    _createdAt: "2023-11-13T10:32:04Z",
    _id: "f9f67163-4f2c-4a96-902a-9829a990601a",
    _rev: "P8iX8yLNzdMX2eS89dcEhH",
    _type: "feature",
    _updatedAt: "2023-11-13T10:32:04Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block trackers",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-trackers",
    },
  },
];
