// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { FeatureCategory } from "../schema.js";

export const featureCategories: FeatureCategory[] = [
  {
    _createdAt: "2023-11-12T10:54:19Z",
    _id: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
    _rev: "01fz37KtvhMj2e8zIIEFoC",
    _type: "featureCategory",
    _updatedAt: "2023-11-18T21:48:48Z",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "ic:baseline-privacy-tip",
        metadata: {
          author: {
            name: "Material Design Authors",
            url: "https://github.com/material-icons/material-icons",
          },
          collectionId: "ic",
          collectionName: "Google Material Icons",
          downloadUrl:
            "https://api.iconify.design/ic:baseline-privacy-tip.svg?width=20&height=20&download=1",
          flip: "",
          hFlip: false,
          iconName: "baseline-privacy-tip",
          inlineSvg:
            '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12c5.16-1.26 9-6.45 9-12V5l-9-4zm-1 6h2v2h-2V7zm0 4h2v6h-2v-6z" fill="currentColor"></path></svg>',
          license: {
            name: "Apache 2.0",
            url: "https://github.com/material-icons/material-icons/blob/master/LICENSE",
          },
          palette: false,
          rotate: 0,
          size: {
            height: 20,
            width: 20,
          },
          url: "https://api.iconify.design/ic:baseline-privacy-tip.svg?width=20&height=20",
          vFlip: false,
        },
      },
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Privacy & Security",
      },
    ],
    slug: {
      _type: "slug",
      current: "privacy-and-security",
    },
  },
  {
    _createdAt: "2023-11-13T10:26:14Z",
    _id: "9fc60c51-bd38-40f9-8714-0295719eae1a",
    _rev: "6tBtT7HSXJBZgGx8QxJnnh",
    _type: "featureCategory",
    _updatedAt: "2023-11-15T10:00:21Z",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "mdi:puzzle",
        metadata: {
          author: {
            name: "Pictogrammers",
            url: "https://github.com/Templarian/MaterialDesign",
          },
          collectionId: "mdi",
          collectionName: "Material Design Icons",
          downloadUrl:
            "https://api.iconify.design/mdi:puzzle.svg?width=20&height=20&download=1",
          hFlip: false,
          iconName: "puzzle",
          inlineSvg:
            '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M20.5 11H19V7a2 2 0 0 0-2-2h-4V3.5A2.5 2.5 0 0 0 10.5 1A2.5 2.5 0 0 0 8 3.5V5H4a2 2 0 0 0-2 2v3.8h1.5c1.5 0 2.7 1.2 2.7 2.7c0 1.5-1.2 2.7-2.7 2.7H2V20a2 2 0 0 0 2 2h3.8v-1.5c0-1.5 1.2-2.7 2.7-2.7c1.5 0 2.7 1.2 2.7 2.7V22H17a2 2 0 0 0 2-2v-4h1.5a2.5 2.5 0 0 0 2.5-2.5a2.5 2.5 0 0 0-2.5-2.5Z" fill="currentColor"></path></svg>',
          license: {
            name: "Apache 2.0",
            url: "https://github.com/Templarian/MaterialDesign/blob/master/LICENSE",
          },
          palette: false,
          rotate: 0,
          size: {
            height: 20,
            width: 20,
          },
          url: "https://api.iconify.design/mdi:puzzle.svg?width=20&height=20",
          vFlip: false,
        },
      },
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Plugins",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Plugins",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Plugins",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "प्लगइन्स",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Plugin",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Плагины",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Vifaa vya ziada",
      },
    ],
    slug: {
      _type: "slug",
      current: "plugins",
    },
  },
  {
    _createdAt: "2023-11-13T10:30:25Z",
    _id: "c6589281-e38e-41ac-b49e-124d1eab39e0",
    _rev: "g4WGtXEJHMGyIQGoBzvMyS",
    _type: "featureCategory",
    _updatedAt: "2023-11-15T10:03:34Z",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "vaadin:tools",
        metadata: {
          author: {
            name: "Vaadin",
            url: "https://github.com/vaadin/web-components",
          },
          collectionId: "vaadin",
          collectionName: "Vaadin Icons",
          downloadUrl:
            "https://api.iconify.design/vaadin:tools.svg?width=20&height=20&download=1",
          flip: "",
          hFlip: false,
          iconName: "tools",
          inlineSvg:
            '<svg viewBox="0 0 16 16" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="m10.3 8.2l-.9.9l.9.9l-1.2 1.2l4.3 4.3c.6.6 1.5.6 2.1 0s.6-1.5 0-2.1l-5.2-5.2zm3.9 6.8c-.4 0-.8-.3-.8-.8c0-.4.3-.8.8-.8s.8.3.8.8s-.3.8-.8.8zM3.6 8l.9-.6L6 5.7l.9.9l.9-.9l-.1-.1c.2-.5.3-1 .3-1.6c0-2.2-1.8-4-4-4c-.6 0-1.1.1-1.6.3l2.9 2.9l-2.1 2.1L.3 2.4C.1 2.9 0 3.4 0 4c0 2.1 1.6 3.7 3.6 4z" fill="currentColor"></path><path d="m8 10.8l.9-.8l-.9-.9l5.7-5.7l1.2-.4L16 .8l-.7-.7l-2.3 1l-.5 1.2L6.9 8L6 7.1l-.8.9s.8.6-.1 1.5c-.5.5-1.3-.1-2.8 1.4L.2 13s-.6 1 .6 2.2s2.2.6 2.2.6l2.1-2.1c1.4-1.4.9-2.3 1.3-2.7c.9-.9 1.6-.2 1.6-.2zm-3.1-.4l.7.7l-3.8 3.8l-.7-.7z" fill="currentColor"></path></svg>',
          license: {
            name: "Apache 2.0",
          },
          palette: false,
          rotate: 0,
          size: {
            height: 20,
            width: 20,
          },
          url: "https://api.iconify.design/vaadin:tools.svg?width=20&height=20",
          vFlip: false,
        },
      },
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Productivity",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Ufanisi",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Продуктивность",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Produktivitas",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Produktivität",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Productiviteit",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "उत्पादकता",
      },
    ],
    slug: {
      _type: "slug",
      current: "productivity",
    },
  },
  {
    _createdAt: "2023-11-13T10:24:00Z",
    _id: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
    _rev: "g4WGtXEJHMGyIQGoBzvNlX",
    _type: "featureCategory",
    _updatedAt: "2023-11-15T10:03:40Z",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "uil:window",
        metadata: {
          author: {
            name: "Iconscout",
            url: "https://github.com/Iconscout/unicons",
          },
          collectionId: "uil",
          collectionName: "Unicons",
          downloadUrl:
            "https://api.iconify.design/uil:window.svg?width=20&height=20&download=1",
          flip: "",
          hFlip: false,
          iconName: "window",
          inlineSvg:
            '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M10 5a1 1 0 1 0 1 1a1 1 0 0 0-1-1ZM6 5a1 1 0 1 0 1 1a1 1 0 0 0-1-1Zm8 0a1 1 0 1 0 1 1a1 1 0 0 0-1-1Zm6-4H4a3 3 0 0 0-3 3v16a3 3 0 0 0 3 3h16a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3Zm1 19a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-9h18Zm0-11H3V4a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1Z" fill="currentColor"></path></svg>',
          license: {
            name: "Apache 2.0",
            url: "https://github.com/Iconscout/unicons/blob/master/LICENSE",
          },
          palette: false,
          rotate: 0,
          size: {
            height: 20,
            width: 20,
          },
          url: "https://api.iconify.design/uil:window.svg?width=20&height=20",
          vFlip: false,
        },
      },
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Interface",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Kiolesura",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Интерфейс",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Antarmuka",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Schnittstelle",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Interface",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "इंटरफेस",
      },
    ],
    slug: {
      _type: "slug",
      current: "interface",
    },
  },
  {
    _createdAt: "2023-11-13T10:20:34Z",
    _id: "f77b7ce5-70cb-4956-84ab-12ea1ce7cc6c",
    _rev: "g4WGtXEJHMGyIQGoBzvF9Q",
    _type: "featureCategory",
    _updatedAt: "2023-11-15T10:02:29Z",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "ic:baseline-security",
        metadata: {
          author: {
            name: "Material Design Authors",
            url: "https://github.com/material-icons/material-icons",
          },
          collectionId: "ic",
          collectionName: "Google Material Icons",
          downloadUrl:
            "https://api.iconify.design/ic:baseline-security.svg?width=20&height=20&download=1",
          flip: "",
          hFlip: false,
          iconName: "baseline-security",
          inlineSvg:
            '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12c5.16-1.26 9-6.45 9-12V5l-9-4zm0 10.99h7c-.53 4.12-3.28 7.79-7 8.94V12H5V6.3l7-3.11v8.8z" fill="currentColor"></path></svg>',
          license: {
            name: "Apache 2.0",
            url: "https://github.com/material-icons/material-icons/blob/master/LICENSE",
          },
          palette: false,
          rotate: 0,
          size: {
            height: 20,
            width: 20,
          },
          url: "https://api.iconify.design/ic:baseline-security.svg?width=20&height=20",
          vFlip: false,
        },
      },
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Security",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Veiligheid",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Sicherheit",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "सुरक्षा",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Keamanan",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Безопасность",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Usalama",
      },
    ],
    slug: {
      _type: "slug",
      current: "security",
    },
  },
];
