// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { Feature } from "../schema.js";

export const features: Feature[] = [
  {
    _createdAt: "2023-11-13T10:35:40Z",
    _id: "30d67e62-0f8c-4648-ab91-dfca41410412",
    _rev: "P8iX8yLNzdMX2eS89iB4I6",
    _type: "feature",
    _updatedAt: "2023-11-15T10:02:44Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Plugins support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor plugins",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Plugin-Unterstützung",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "प्लगइन समर्थन करते हैं।",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan plugin",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка плагинов",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa programu zinazoweza kuongezwa",
      },
    ],
    slug: {
      _type: "slug",
      current: "plugins-support",
    },
  },
  {
    _createdAt: "2023-11-12T10:59:32Z",
    _id: "3c42fbee-fa58-4c34-82b4-07324a097635",
    _rev: "g4WGtXEJHMGyIQGoBzvVGM",
    _type: "feature",
    _updatedAt: "2023-11-15T10:06:03Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    description: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Blocks ads from appearing on websites",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeert advertenties die op websites verschijnen",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Blockiert Anzeigen, die auf Websites erscheinen.",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "वेबसाइटों पर विज्ञापनों को दिखान",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Memblokir iklan agar tidak muncul di situs web.",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокирует появление рекламы на веб-сайтах",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Inazuia matangazo kuonekana kwenye tovuti.",
      },
    ],
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block ads",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Zuia matangazo",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокировать рекламу",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Blokir iklan",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Werbung blockieren",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeer advertenties",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "विज्ञापनों को ब्लॉक करें",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-ads",
    },
  },
  {
    _createdAt: "2023-11-13T10:34:48Z",
    _id: "4a4fce62-dc7d-40d9-b1a5-84e6a92366e2",
    _rev: "P8iX8yLNzdMX2eS89iBE4s",
    _type: "feature",
    _updatedAt: "2023-11-15T10:06:38Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Private browsing",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Privé browsen",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Privates Surfen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "निजी ब्राउज़िंग",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Penjelajahan pribadi",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Приватный режим просмотра",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Kuvinjari faragha",
      },
    ],
    slug: {
      _type: "slug",
      current: "private-browsing",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:28Z",
    _id: "a32cbcd7-c281-45f5-9041-a6d2e1e26767",
    _rev: "6tBtT7HSXJBZgGx8QxKt8j",
    _type: "feature",
    _updatedAt: "2023-11-15T10:08:13Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Password manager",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Wachtwoordbeheerder",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Passwort-Manager",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "पासवर्ड प्रबंधक",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Manajer kata sandi",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Менеджер паролей",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Meneja wa nywila",
      },
    ],
    slug: {
      _type: "slug",
      current: "password-manager",
    },
  },
  {
    _createdAt: "2023-11-13T23:34:38Z",
    _id: "bb5f2721-c9ca-4421-a8ba-d6cd023e7617",
    _rev: "P8iX8yLNzdMX2eS89iBGo8",
    _type: "feature",
    _updatedAt: "2023-11-15T10:08:54Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Picture-in-Picture",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Beeld-in-beeld",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Bild-im-Bild",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "पिक्चर-इन-पिक्चर",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Gambar dalam Gambar",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Картинка в картинке",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Picha-ndani-ya-Picha",
      },
    ],
    slug: {
      _type: "slug",
      current: "picture-in-picture",
    },
  },
  {
    _createdAt: "2023-11-13T10:36:23Z",
    _id: "bd5e7853-c514-4498-9b92-82ec06c78122",
    _rev: "6tBtT7HSXJBZgGx8QxKylV",
    _type: "feature",
    _updatedAt: "2023-11-15T10:09:10Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Chrome web store support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor de Chrome webwinkel",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Unterstützung für den Chrome Web Store",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "क्रोम वेब स्टोर समर्थन",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan toko web Chrome",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка Chrome веб-магазина",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa duka la wavuti la Chrome",
      },
    ],
    slug: {
      _type: "slug",
      current: "chrome-web-store-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:35:21Z",
    _id: "e5ec9ff5-d466-4d4c-976c-48b3bf104e3f",
    _rev: "P8iX8yLNzdMX2eS89iBKar",
    _type: "feature",
    _updatedAt: "2023-11-15T10:09:48Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Firefox add-ons support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor Firefox-add-ons",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Unterstützung für Firefox-Erweiterungen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "फ़ायरफ़ॉक्स एड-ऑन्स समर्थ",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan add-ons Firefox",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка дополнений для Firefox",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa nyongeza za Firefox",
      },
    ],
    slug: {
      _type: "slug",
      current: "firefox-add-ons-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:04Z",
    _id: "f90318ae-0fb2-487c-a384-bc3cfb534c57",
    _rev: "P8iX8yLNzdMX2eS89iBN8w",
    _type: "feature",
    _updatedAt: "2023-11-15T10:11:12Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Cloud sync",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Cloud synchronisatie",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Cloud-Synchronisierung",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "क्लाउड सिंक",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Sinkronisasi awan",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Синхронизация в облаке",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Sawia ya wingu",
      },
    ],
    slug: {
      _type: "slug",
      current: "cloud-sync",
    },
  },
  {
    _createdAt: "2023-11-13T10:32:04Z",
    _id: "f9f67163-4f2c-4a96-902a-9829a990601a",
    _rev: "P8iX8yLNzdMX2eS89iBNzd",
    _type: "feature",
    _updatedAt: "2023-11-15T10:11:37Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block trackers",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeer trackers",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Tracker blockieren",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "ट्रैकर्स को ब्लॉक करें।",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Blokir pelacak",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокировать трекеры",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Zuia wafuatiliaji",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-trackers",
    },
  },
];
