// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { Feature } from "../schema.js";

export const features: Feature[] = [
  {
    _createdAt: "2023-11-13T10:35:40Z",
    _id: "30d67e62-0f8c-4648-ab91-dfca41410412",
    _rev: "7kaIE0fx1bl03pWpFuW00g",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:33Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Plugins support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor plugins",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Prise en charge des plugins",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Plugin-Unterstützung",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "प्लगइन समर्थन करते हैं।",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan plugin",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка плагинов",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Soporte de plugins",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa programu zinazoweza kuongezwa",
      },
    ],
    slug: {
      _type: "slug",
      current: "plugins-support",
    },
  },
  {
    _createdAt: "2023-11-12T10:59:32Z",
    _id: "3c42fbee-fa58-4c34-82b4-07324a097635",
    _rev: "o6EKSRmXrHYie9DfoEIsMm",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:39Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    description: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Blocks ads from appearing on websites",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeert advertenties die op websites verschijnen",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Bloque les publicités qui apparaissent sur les sites web.",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Blockiert Anzeigen, die auf Websites erscheinen.",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "वेबसाइटों पर विज्ञापनों को दिखान",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Memblokir iklan agar tidak muncul di situs web.",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокирует появление рекламы на веб-сайтах",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Bloquea los anuncios que aparecen en los sitios web.",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Inazuia matangazo kuonekana kwenye tovuti.",
      },
    ],
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block ads",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeer advertenties",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Bloquer les publicités",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Werbung blockieren",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "विज्ञापनों को ब्लॉक करें",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Blokir iklan",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокировать рекламу",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Bloquear anuncios",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Zuia matangazo",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-ads",
    },
  },
  {
    _createdAt: "2023-11-13T10:34:48Z",
    _id: "4a4fce62-dc7d-40d9-b1a5-84e6a92366e2",
    _rev: "7kaIE0fx1bl03pWpFuW0Da",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:41Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Private browsing",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Privé browsen",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Navigation privée",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Privates Surfen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "निजी ब्राउज़िंग",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Penjelajahan pribadi",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Приватный режим просмотра",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Navegación privada",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Kuvinjari faragha",
      },
    ],
    slug: {
      _type: "slug",
      current: "private-browsing",
    },
  },
  {
    _createdAt: "2023-11-18T21:07:39Z",
    _id: "5f610b9c-edab-4ced-a6f2-fec473db5c82",
    _rev: "7kaIE0fx1bl03pWpFuW0K2",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:43Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Dark mode",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Donkere modus",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Mode sombre",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Dunkler Modus",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "डार्क मोड",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Mode gelap",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Темный режим",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Modo oscuro",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Njia ya giza",
      },
    ],
    slug: {
      _type: "slug",
      current: "dark-mode",
    },
  },
  {
    _createdAt: "2023-11-18T21:06:07Z",
    _id: "7dd7c5a3-4a52-4eb0-b24c-fe99c08359e1",
    _rev: "yf6YE3Avm57l7p1xz1cv5h",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:45Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Autofill forms",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Automatisch invullen van formulieren",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Remplir automatiquement les formulaires",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Formulare automatisch ausfüllen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "ऑटोफिल फॉर्म्स",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Isi formulir otomatis",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Автозаполнение форм",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Rellenar formularios automáticamente",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Jaza fomu kiotomatiki",
      },
    ],
    slug: {
      _type: "slug",
      current: "autofill-forms",
    },
  },
  {
    _createdAt: "2023-11-18T21:06:56Z",
    _id: "9aaeeeb8-0124-424c-9d76-1cb34a7d79bc",
    _rev: "o6EKSRmXrHYie9DfoEIt58",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:46Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Multiple profiles",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Meerdere profielen",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Profils multiples",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Mehrere Profile",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "एकाधिक प्रोफ़ाइलें",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Profil ganda",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Несколько профилей",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Perfiles múltiples",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Profaili nyingi",
      },
    ],
    slug: {
      _type: "slug",
      current: "multiple-profiles",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:28Z",
    _id: "a32cbcd7-c281-45f5-9041-a6d2e1e26767",
    _rev: "o6EKSRmXrHYie9DfoEIupM",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:48Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Password manager",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Wachtwoordbeheerder",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Gestionnaire de mots de passe",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Passwort-Manager",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "पासवर्ड प्रबंधक",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Manajer kata sandi",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Менеджер паролей",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Gestor de contraseñas",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Meneja wa nywila",
      },
    ],
    slug: {
      _type: "slug",
      current: "password-manager",
    },
  },
  {
    _createdAt: "2023-11-18T21:08:16Z",
    _id: "ae11cc57-7376-42c2-82fc-a65da2c5fe14",
    _rev: "7kaIE0fx1bl03pWpFuW7cw",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:50Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Reader mode",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Leesmodus",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Mode lecture",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Lesemodus",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "पाठक मोड",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Mode pembaca",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Режим чтения",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Modo de lectura",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Mode ya kusoma",
      },
    ],
    slug: {
      _type: "slug",
      current: "reader-mode",
    },
  },
  {
    _createdAt: "2023-11-18T21:04:16Z",
    _id: "ae398af0-f21a-4ccf-a7e9-0527e05e436d",
    _rev: "yf6YE3Avm57l7p1xz1d56L",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:52Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Tab groups",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Tabgroepen",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Groupes d'onglets",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Tab-Gruppen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "टैब समूह",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Kelompok tab",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Группы вкладок",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Grupos de pestañas",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Vikundi vya tab",
      },
    ],
    slug: {
      _type: "slug",
      current: "tab-groups",
    },
  },
  {
    _createdAt: "2023-11-13T23:34:38Z",
    _id: "bb5f2721-c9ca-4421-a8ba-d6cd023e7617",
    _rev: "yf6YE3Avm57l7p1xz1d8tB",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:54Z",
    category: {
      _ref: "dc26e05f-38e2-4a4a-9fd6-6c0e1b2cdda7",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Picture-in-Picture",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Beeld-in-beeld",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Image dans l'image",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Bild-im-Bild",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "पिक्चर-इन-पिक्चर",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Gambar dalam Gambar",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Картинка в картинке",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Imagen en imagen",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Picha-ndani-ya-Picha",
      },
    ],
    slug: {
      _type: "slug",
      current: "picture-in-picture",
    },
  },
  {
    _createdAt: "2023-11-13T10:36:23Z",
    _id: "bd5e7853-c514-4498-9b92-82ec06c78122",
    _rev: "yf6YE3Avm57l7p1xz1dA6f",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:56Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Chrome web store support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor de Chrome webwinkel",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Support de Chrome Web Store",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Unterstützung für den Chrome Web Store",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "क्रोम वेब स्टोर समर्थन",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan toko web Chrome",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка Chrome веб-магазина",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Soporte de la tienda web de Chrome",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa duka la wavuti la Chrome",
      },
    ],
    slug: {
      _type: "slug",
      current: "chrome-web-store-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:35:21Z",
    _id: "e5ec9ff5-d466-4d4c-976c-48b3bf104e3f",
    _rev: "7kaIE0fx1bl03pWpFuW8i2",
    _type: "feature",
    _updatedAt: "2025-03-16T10:23:58Z",
    category: {
      _ref: "9fc60c51-bd38-40f9-8714-0295719eae1a",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Firefox add-ons support",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Ondersteuning voor Firefox-add-ons",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Prise en charge des extensions Firefox",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Unterstützung für Firefox-Erweiterungen",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "फ़ायरफ़ॉक्स एड-ऑन्स समर्थ",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Dukungan add-ons Firefox",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Поддержка дополнений для Firefox",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Soporte de complementos de Firefox",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Msaada wa nyongeza za Firefox",
      },
    ],
    slug: {
      _type: "slug",
      current: "firefox-add-ons-support",
    },
  },
  {
    _createdAt: "2023-11-13T10:33:04Z",
    _id: "f90318ae-0fb2-487c-a384-bc3cfb534c57",
    _rev: "yf6YE3Avm57l7p1xz1dX2H",
    _type: "feature",
    _updatedAt: "2025-03-16T10:24:00Z",
    category: {
      _ref: "c6589281-e38e-41ac-b49e-124d1eab39e0",
      _type: "reference",
    },
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Cloud sync",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Cloud synchronisatie",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Synchronisation dans le cloud",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Cloud-Synchronisierung",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "क्लाउड सिंक",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Sinkronisasi awan",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Синхронизация в облаке",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Sincronización en la nube",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Sawia ya wingu",
      },
    ],
    slug: {
      _type: "slug",
      current: "cloud-sync",
    },
  },
  {
    _createdAt: "2023-11-13T10:32:04Z",
    _id: "f9f67163-4f2c-4a96-902a-9829a990601a",
    _rev: "o6EKSRmXrHYie9DfoEJ1mU",
    _type: "feature",
    _updatedAt: "2025-03-16T10:24:04Z",
    category: {
      _ref: "645f3d5f-3eae-4e8a-956e-151b7cc36fe4",
      _type: "reference",
    },
    description: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block third-party cookies and social trackers",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeer cookies van derden en sociale trackers",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Bloquez les cookies tiers et les traceurs sociaux.",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Blockieren Sie Cookies von Drittanbietern und soziale Tracker.",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "तृतीय-पक्ष कुकीज़ और सामाजिक ट",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Blokir cookie pihak ketiga dan pelacak sosial",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокировать сторонние файлы cookie и социальные трекеры",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Bloquear cookies de terceros y rastreadores sociales.",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Zuia kuki za watu wengine na wafuatiliaji wa kijamii",
      },
    ],
    name: [
      {
        _key: "en",
        _type: "internationalizedArrayStringValue",
        value: "Block trackers",
      },
      {
        _key: "nl",
        _type: "internationalizedArrayStringValue",
        value: "Blokkeer trackers",
      },
      {
        _key: "fr",
        _type: "internationalizedArrayStringValue",
        value: "Bloquer les traceurs",
      },
      {
        _key: "de",
        _type: "internationalizedArrayStringValue",
        value: "Tracker blockieren",
      },
      {
        _key: "hi",
        _type: "internationalizedArrayStringValue",
        value: "ट्रैकर्स को ब्लॉक करें।",
      },
      {
        _key: "id",
        _type: "internationalizedArrayStringValue",
        value: "Blokir pelacak",
      },
      {
        _key: "ru",
        _type: "internationalizedArrayStringValue",
        value: "Блокировать трекеры",
      },
      {
        _key: "es",
        _type: "internationalizedArrayStringValue",
        value: "Bloquear rastreadores",
      },
      {
        _key: "sw",
        _type: "internationalizedArrayStringValue",
        value: "Zuia wafuatiliaji",
      },
    ],
    slug: {
      _type: "slug",
      current: "block-trackers",
    },
  },
];
