// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { Language } from "../schema.js";

export const languages: Language[] = [
  {
    _createdAt: "2023-10-02T10:17:37Z",
    _id: "cef5f9a9-5f4f-46db-96be-0228c9a760ab",
    _rev: "ne2Lo8XNb3UQT3zNABRyOf",
    _type: "language",
    _updatedAt: "2023-10-04T17:30:25Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:nl-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:nl-4x3.svg?width=20&height=20&download=1",
        hFlip: false,
        iconName: "nl-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h640v480H0z" fill="#21468b"></path><path d="M0 0h640v320H0z" fill="#fff"></path><path d="M0 0h640v160H0z" fill="#ae1c28"></path></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:nl-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "nl",
    name: "Dutch",
  },
  {
    _createdAt: "2023-10-02T10:17:27Z",
    _id: "18b3bfa7-f421-4c7f-8208-61c4d02e98c3",
    _rev: "uzKWDNHSv1RNm7kJ3WQ1fI",
    _type: "language",
    _updatedAt: "2023-10-04T17:30:15Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:gb-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:gb-4x3.svg?width=20&height=20&download=1",
        hFlip: false,
        iconName: "gb-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h640v480H0z" fill="#012169"></path><path d="m75 0l244 181L562 0h78v62L400 241l240 178v61h-80L320 301L81 480H0v-60l239-178L0 64V0h75z" fill="#FFF"></path><path d="m424 281l216 159v40L369 281h55zm-184 20l6 35L54 480H0l240-179zM640 0v3L391 191l2-44L590 0h50zM0 0l239 176h-60L0 42V0z" fill="#C8102E"></path><path d="M241 0v480h160V0H241zM0 160v160h640V160H0z" fill="#FFF"></path><path d="M0 193v96h640v-96H0zM273 0v480h96V0h-96z" fill="#C8102E"></path></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:gb-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "en",
    name: "English",
  },
  {
    _createdAt: "2023-10-23T14:39:09Z",
    _id: "bf1dee63-2cf3-4bb2-8500-120d6017cccf",
    _rev: "7V6W77YnYTSXWZozOaBuyR",
    _type: "language",
    _updatedAt: "2023-10-23T14:39:09Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:de-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:de-4x3.svg?width=20&height=20&download=1",
        flip: "",
        hFlip: false,
        iconName: "de-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 320h640v160H0z" fill="#ffce00"></path><path d="M0 0h640v160H0z"></path><path d="M0 160h640v160H0z" fill="#d00"></path></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:de-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "de",
    name: "German",
  },
  {
    _createdAt: "2023-11-01T15:45:56Z",
    _id: "d8d05980-0e90-4097-a466-4c1676cf9470",
    _rev: "lRZ54YVKpJaKWrGZ7QPbBx",
    _type: "language",
    _updatedAt: "2023-11-01T15:45:56Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:in-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:in-4x3.svg?width=20&height=20&download=1",
        flip: "",
        hFlip: false,
        iconName: "in-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h640v160H0z" fill="#f93"></path><path d="M0 160h640v160H0z" fill="#fff"></path><path d="M0 320h640v160H0z" fill="#128807"></path><g transform="matrix(3.2 0 0 3.2 320 240)"><circle fill="#008" r="20"></circle><circle fill="#fff" r="17.5"></circle><circle fill="#008" r="3.5"></circle><g id="IconifyId18b89d90a0aae8dd74"><g id="IconifyId18b89d90a0aae8dd75"><g id="IconifyId18b89d90a0aae8dd76"><g fill="#008" id="IconifyId18b89d90a0aae8dd77"><circle transform="rotate(7.5 -8.8 133.5)" r=".9"></circle><path d="M0 17.5L.6 7L0 2l-.6 5L0 17.5z"></path></g></g></g></g></g></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:in-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "hi",
    name: "Hindi",
  },
  {
    _createdAt: "2023-10-02T10:43:21Z",
    _id: "5a5f235a-a587-4fbc-80b4-8391784b7098",
    _rev: "aO8M0JobkfhvTnYZtWBnSJ",
    _type: "language",
    _updatedAt: "2023-10-07T15:40:04Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:id-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:id-4x3.svg?width=20&height=20&download=1",
        flip: "",
        hFlip: false,
        iconName: "id-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h640v240H0Z" fill="#e70011"></path><path d="M0 240h640v240H0Z" fill="#fff"></path></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:id-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "id",
    name: "Indonesian",
  },
  {
    _createdAt: "2023-11-01T15:46:17Z",
    _id: "50aeb3da-600d-4883-bfed-d2b14248da04",
    _rev: "h9gndD2P4keuz4rjs4xnrx",
    _type: "language",
    _updatedAt: "2023-11-01T15:46:17Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:ru-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:ru-4x3.svg?width=20&height=20&download=1",
        flip: "",
        hFlip: false,
        iconName: "ru-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><g stroke-width="1pt" fill-rule="evenodd"><path d="M0 0h640v480H0z" fill="#fff"></path><path d="M0 160h640v320H0z" fill="#0039a6"></path><path d="M0 320h640v160H0z" fill="#d52b1e"></path></g></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:ru-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "ru",
    name: "Russian",
  },
  {
    _createdAt: "2023-11-02T06:20:11Z",
    _id: "4a57ee2c-d7f4-4305-b25c-b428fe6707aa",
    _rev: "B4UTUzmTSUGGaDoK0OLtbs",
    _type: "language",
    _updatedAt: "2023-11-02T06:20:11Z",
    flag: {
      _type: "icon.manager",
      icon: "flag:ke-4x3",
      metadata: {
        author: {
          name: "Panayiotis Lipiridis",
          url: "https://github.com/lipis/flag-icons",
        },
        collectionId: "flag",
        collectionName: "Flag Icons",
        downloadUrl:
          "https://api.iconify.design/flag:ke-4x3.svg?width=20&height=20&download=1",
        flip: "",
        hFlip: false,
        iconName: "ke-4x3",
        inlineSvg:
          '<svg viewBox="0 0 640 480" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><defs><path d="m-28.6 47.5l1.8 1l46.7-81c2.7-.6 4.2-3.2 5.7-5.8c1-1.8 5-8.7 6.7-17.7a58 58 0 0 0-11.9 14.7c-1.5 2.6-3 5.2-2.3 7.9z" stroke-miterlimit="10" fill="#000" id="IconifyId18b8e70413f1c93904"></path></defs><path d="M0 0h640v480H0z" fill="#fff"></path><path d="M0 0h640v144H0z"></path><path d="M0 336h640v144H0z" fill="#060"></path><g transform="matrix(3 0 0 3 320 240)" id="IconifyId18b8e70413f1c93905"></g><path d="M640.5 168H377c-9-24-39-72-57-72s-48 48-57 72H-.2v144H263c9 24 39 72 57 72s48-48 57-72h263.5V168z" fill="#b00"></path><path d="M377 312c9-24 15-48 15-72s-6-48-15-72c-9 24-15 48-15 72s6 48 15 72" fill="#000" id="IconifyId18b8e70413f1c93906"></path><g transform="matrix(3 0 0 3 320 240)" fill="#fff"><ellipse ry="6" rx="4"></ellipse><path d="M1 5.8s4 8 4 21s-4 21-4 21z" id="IconifyId18b8e70413f1c93907"></path></g></svg>',
        license: {
          name: "MIT",
          url: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
        },
        palette: true,
        rotate: 0,
        size: {
          height: 20,
          width: 20,
        },
        url: "https://api.iconify.design/flag:ke-4x3.svg?width=20&height=20",
        vFlip: false,
      },
    },
    id: "sw",
    name: "Swahili",
  },
];
