// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { SanityOS } from "../schema.js";

export const oses: SanityOS[] = [
  {
    _type: "os",
    icon: {
      icon: "logos:ios",
      metadata: {
        flip: "",
        iconName: "ios",
        url: "https://api.iconify.design/logos:ios.svg?width=20&height=20",
        palette: true,
        downloadUrl:
          "https://api.iconify.design/logos:ios.svg?width=20&height=20&download=1",
        size: {
          width: 20,
          height: 20,
        },
        author: {
          name: "Gil Barbara",
          url: "https://github.com/gilbarbara/logos",
        },
        collectionId: "logos",
        hFlip: false,
        collectionName: "SVG Logos",
        license: {
          name: "CC0",
          url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
        },
        rotate: 0,
        vFlip: false,
      },
      _type: "icon.manager",
    },
    _createdAt: "2023-10-07T02:54:01Z",
    _rev: "JkTQlzv8nKmBN7XeR0R6U9",
    name: "iOS",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _updatedAt: "2023-10-14T05:31:34Z",
    homepage: "https://www.apple.com/ios/",
    matchOsName: "iOS",
    vendor: "Apple",
    _id: "0e2dc525-cff5-4ec1-a670-e86684304740",
    slug: {
      current: "ios",
      _type: "slug",
    },
  },
  {
    _id: "2495a35b-5efd-49e6-8999-d248d5285125",
    icon: {
      metadata: {
        rotate: 0,
        downloadUrl:
          "https://api.iconify.design/logos:android-icon.svg?width=20&height=20&download=1",
        collectionName: "SVG Logos",
        palette: true,
        flip: "",
        vFlip: false,
        iconName: "android-icon",
        hFlip: false,
        url: "https://api.iconify.design/logos:android-icon.svg?width=20&height=20",
        size: {
          width: 20,
          height: 20,
        },
        collectionId: "logos",
        author: {
          name: "Gil Barbara",
          url: "https://github.com/gilbarbara/logos",
        },
        license: {
          name: "CC0",
          url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
        },
      },
      _type: "icon.manager",
      icon: "logos:android-icon",
    },
    _rev: "JkTQlzv8nKmBN7XeR0R6Gn",
    _type: "os",
    name: "Android",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    slug: {
      current: "android",
      _type: "slug",
    },
    matchOsName: "Android",
    _createdAt: "2023-10-07T03:10:09Z",
    _updatedAt: "2023-10-14T05:31:23Z",
    vendor: "Open Handset Alliance",
    homepage: "https://www.android.com",
  },
  {
    slug: {
      current: "windows",
      _type: "slug",
    },
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _createdAt: "2023-09-28T05:37:03Z",
    _updatedAt: "2023-10-14T05:32:05Z",
    matchOsName: "Windows",
    icon: {
      metadata: {
        rotate: 0,
        author: {
          name: "Gil Barbara",
          url: "https://github.com/gilbarbara/logos",
        },
        license: {
          name: "CC0",
          url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
        },
        iconName: "microsoft-windows-icon",
        downloadUrl:
          "https://api.iconify.design/logos:microsoft-windows-icon.svg?width=20&height=20&download=1",
        flip: "",
        url: "https://api.iconify.design/logos:microsoft-windows-icon.svg?width=20&height=20",
        palette: true,
        size: {
          width: 20,
          height: 20,
        },
        inlineSvg:
          '<svg viewBox="0 0 256 256" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h121.329v121.329H0V0Zm134.671 0H256v121.329H134.671V0ZM0 134.671h121.329V256H0V134.671Zm134.671 0H256V256H134.671V134.671Z" fill="#0078D4"></path></svg>',
        hFlip: false,
        collectionId: "logos",
        collectionName: "SVG Logos",
        vFlip: false,
      },
      _type: "icon.manager",
      icon: "logos:microsoft-windows-icon",
    },
    name: "Windows",
    _id: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
    homepage: "https://www.microsoft.com/windows",
    vendor: "Microsoft",
    _type: "os",
    _rev: "j8oUcJ9RJBLGMGvSp4sJAY",
  },
  {
    _createdAt: "2023-10-07T03:10:52Z",
    _updatedAt: "2023-10-14T05:31:29Z",
    slug: {
      current: "ubuntu",
      _type: "slug",
    },
    vendor: "Canonical",
    name: "Ubuntu",
    icon: {
      metadata: {
        collectionId: "logos",
        vFlip: false,
        size: {
          width: 20,
          height: 20,
        },
        flip: "",
        url: "https://api.iconify.design/logos:ubuntu.svg?width=20&height=20",
        iconName: "ubuntu",
        author: {
          name: "Gil Barbara",
          url: "https://github.com/gilbarbara/logos",
        },
        license: {
          name: "CC0",
          url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
        },
        palette: true,
        rotate: 0,
        downloadUrl:
          "https://api.iconify.design/logos:ubuntu.svg?width=20&height=20&download=1",
        hFlip: false,
        collectionName: "SVG Logos",
      },
      _type: "icon.manager",
      icon: "logos:ubuntu",
    },
    _id: "efbb0679-8cf1-41f7-85de-6b98b18e637e",
    matchOsName: "Ubuntu",
    _rev: "j8oUcJ9RJBLGMGvSp4sJ86",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _type: "os",
    homepage: "https://ubuntu.com",
  },
  {
    _rev: "4HbZj3khZcB9nAIJRwsJlL",
    _type: "os",
    _id: "ffebb051-7321-4379-aeaa-ef1c726c92b4",
    vendor: "Apple",
    icon: {
      icon: "mdi:apple",
      metadata: {
        rotate: 0,
        license: {
          name: "Apache 2.0",
          url: "https://github.com/Templarian/MaterialDesign/blob/master/LICENSE",
        },
        size: {
          width: 20,
          height: 20,
        },
        vFlip: false,
        downloadUrl:
          "https://api.iconify.design/mdi:apple.svg?width=20&height=20&download=1",
        url: "https://api.iconify.design/mdi:apple.svg?width=20&height=20",
        inlineSvg:
          '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47c-1.34.03-1.77-.79-3.29-.79c-1.53 0-2 .77-3.27.82c-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51c1.28-.02 2.5.87 3.29.87c.78 0 2.26-1.07 3.81-.91c.65.03 2.47.26 3.64 1.98c-.09.06-2.17 1.28-2.15 3.81c.03 3.02 2.65 4.03 2.68 4.04c-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5c.13 1.17-.34 2.35-1.04 3.19c-.69.85-1.83 1.51-2.95 1.42c-.15-1.15.41-2.35 1.05-3.11Z" fill="currentColor"></path></svg>',
        collectionId: "mdi",
        hFlip: false,
        palette: false,
        collectionName: "Material Design Icons",
        iconName: "apple",
        author: {
          name: "Pictogrammers",
          url: "https://github.com/Templarian/MaterialDesign",
        },
      },
      _type: "icon.manager",
    },
    name: "macOS",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    homepage: "https://www.apple.com/macos/",
    matchOsName: "macOS",
    slug: {
      current: "macos",
      _type: "slug",
    },
    _createdAt: "2023-10-05T15:12:50Z",
    _updatedAt: "2023-10-14T05:31:54Z",
  },
];
