// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { OS } from "../schema.js";

export const oses: OS[] = [
  {
    _rev: "Lh7rhBNTpK2mkuYCd9opmk",
    _updatedAt: "2023-10-18T15:20:05Z",
    vendor: "Apple",
    _createdAt: "2023-10-07T02:54:01Z",
    homepage: "https://www.apple.com/ios/",
    name: "iOS",
    icon: {
      predefined: {
        metadata: {
          url: "https://api.iconify.design/logos:ios.svg?width=20&height=20",
          collectionName: "SVG Logos",
          author: {
            name: "Gil Barbara",
            url: "https://github.com/gilbarbara/logos",
          },
          collectionId: "logos",
          size: {
            height: 20,
            width: 20,
          },
          vFlip: false,
          palette: true,
          iconName: "ios",
          license: {
            name: "CC0",
            url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
          },
          inlineSvg:
            '<svg viewBox="0 0 257 128" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M1.862 124.978h21.17v-90.12H1.862v90.12ZM12.405 23.04c6.631 0 11.817-5.101 11.817-11.477C24.222 5.1 19.036 0 12.405 0C5.858 0 .672 5.101.672 11.563c0 6.376 5.186 11.477 11.733 11.477ZM93.515.254c-35.792 0-58.238 24.401-58.238 63.426c0 39.024 22.444 63.34 58.239 63.34c35.707 0 58.153-24.316 58.153-63.34c0-39.025-22.444-63.426-58.153-63.426Zm0 18.705c21.85 0 35.793 17.344 35.793 44.72c0 27.291-13.943 44.636-35.792 44.636c-21.935 0-35.793-17.344-35.793-44.636c0-27.376 13.859-44.72 35.793-44.72ZM160.6 90.46c.935 22.616 19.469 36.558 47.695 36.558c29.672 0 48.377-14.623 48.377-37.919c0-18.279-10.542-28.566-35.453-34.262l-14.113-3.23c-15.049-3.571-21.255-8.332-21.255-16.494c0-10.203 9.352-17.004 23.21-17.004c14.028 0 23.635 6.887 24.656 18.364h20.914c-.51-21.595-18.364-36.219-45.4-36.219c-26.696 0-45.655 14.708-45.655 36.474c0 17.514 10.712 28.396 33.326 33.583l15.899 3.74c15.473 3.657 21.765 8.758 21.765 17.6c0 10.202-10.288 17.514-25.08 17.514c-14.963 0-26.27-7.397-27.63-18.705H160.6Z"></path></svg>',
          rotate: 0,
          hFlip: false,
          downloadUrl:
            "https://api.iconify.design/logos:ios.svg?width=20&height=20&download=1",
          flip: "",
        },
        _type: "icon.manager",
        icon: "logos:ios",
      },
      _type: "icon",
    },
    _id: "0e2dc525-cff5-4ec1-a670-e86684304740",
    slug: {
      current: "ios",
      _type: "slug",
    },
    matchOsName: "iOS",
    _type: "os",
    description: {
      nl: null,
      en: null,
      id: null,
    },
  },
  {
    _rev: "Lh7rhBNTpK2mkuYCd9orco",
    _type: "os",
    name: "Android",
    slug: {
      current: "android",
      _type: "slug",
    },
    matchOsName: "Android",
    _id: "2495a35b-5efd-49e6-8999-d248d5285125",
    icon: {
      _type: "icon",
      predefined: {
        metadata: {
          collectionId: "logos",
          author: {
            url: "https://github.com/gilbarbara/logos",
            name: "Gil Barbara",
          },
          license: {
            name: "CC0",
            url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
          },
          size: {
            width: 20,
            height: 20,
          },
          inlineSvg:
            '<svg viewBox="0 0 256 145" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="m190.736 43.58l21.305-36.927a4.443 4.443 0 0 0-1.623-6.06a4.436 4.436 0 0 0-6.055 1.625l-21.57 37.395C166.294 32.079 147.768 27.882 128 27.882s-38.297 4.197-54.792 11.731L51.637 2.217A4.437 4.437 0 0 0 45.581.593a4.44 4.44 0 0 0-1.622 6.06L65.264 43.58C28.681 63.494 3.66 100.56 0 144.35h256c-3.663-43.79-28.685-80.856-65.264-100.77m-3.921 42.95c5.828 0 10.568 4.829 10.568 10.764c0 5.937-4.74 10.769-10.568 10.769c-5.826 0-10.566-4.832-10.566-10.769c0-5.935 4.74-10.764 10.566-10.764Zm-117.631 0c5.826 0 10.567 4.829 10.567 10.764c0 5.937-4.741 10.769-10.567 10.769c-5.828 0-10.567-4.832-10.567-10.769c0-5.935 4.74-10.764 10.567-10.764Z" fill="#3DDC84"></path></svg>',
          hFlip: false,
          url: "https://api.iconify.design/logos:android-icon.svg?width=20&height=20",
          downloadUrl:
            "https://api.iconify.design/logos:android-icon.svg?width=20&height=20&download=1",
          vFlip: false,
          flip: "",
          palette: true,
          iconName: "android-icon",
          rotate: 0,
          collectionName: "SVG Logos",
        },
        _type: "icon.manager",
        icon: "logos:android-icon",
      },
    },
    _createdAt: "2023-10-07T03:10:09Z",
    vendor: "Open Handset Alliance",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _updatedAt: "2023-10-18T15:20:23Z",
    homepage: "https://www.android.com",
  },
  {
    _createdAt: "2023-09-28T05:37:03Z",
    icon: {
      predefined: {
        metadata: {
          inlineSvg:
            '<svg viewBox="0 0 256 256" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h121.329v121.329H0V0Zm134.671 0H256v121.329H134.671V0ZM0 134.671h121.329V256H0V134.671Zm134.671 0H256V256H134.671V134.671Z" fill="#0078D4"></path></svg>',
          flip: "",
          collectionName: "SVG Logos",
          hFlip: false,
          url: "https://api.iconify.design/logos:microsoft-windows-icon.svg?width=20&height=20",
          author: {
            name: "Gil Barbara",
            url: "https://github.com/gilbarbara/logos",
          },
          rotate: 0,
          vFlip: false,
          palette: true,
          downloadUrl:
            "https://api.iconify.design/logos:microsoft-windows-icon.svg?width=20&height=20&download=1",
          iconName: "microsoft-windows-icon",
          collectionId: "logos",
          license: {
            name: "CC0",
            url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
          },
          size: {
            width: 20,
            height: 20,
          },
        },
        _type: "icon.manager",
        icon: "logos:microsoft-windows-icon",
      },
      _type: "icon",
    },
    _updatedAt: "2023-10-18T15:18:26Z",
    name: "Windows",
    _id: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
    homepage: "https://www.microsoft.com/windows",
    vendor: "Microsoft",
    _rev: "7V6W77YnYTSXWZozOSgvMz",
    matchOsName: "Windows",
    _type: "os",
    slug: {
      current: "windows",
      _type: "slug",
    },
    description: {
      nl: null,
      en: null,
      id: null,
    },
  },
  {
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _id: "efbb0679-8cf1-41f7-85de-6b98b18e637e",
    _updatedAt: "2023-10-18T15:19:48Z",
    matchOsName: "Ubuntu",
    _createdAt: "2023-10-07T03:10:52Z",
    _rev: "Lh7rhBNTpK2mkuYCd9op0U",
    icon: {
      predefined: {
        metadata: {
          url: "https://api.iconify.design/logos:ubuntu.svg?width=20&height=20",
          license: {
            name: "CC0",
            url: "https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt",
          },
          flip: "",
          collectionName: "SVG Logos",
          author: {
            name: "Gil Barbara",
            url: "https://github.com/gilbarbara/logos",
          },
          iconName: "ubuntu",
          downloadUrl:
            "https://api.iconify.design/logos:ubuntu.svg?width=20&height=20&download=1",
          palette: true,
          size: {
            width: 20,
            height: 20,
          },
          collectionId: "logos",
          rotate: 0,
          vFlip: false,
          inlineSvg:
            '<svg viewBox="0 0 256 256" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M255.637 127.683c0 70.514-57.165 127.68-127.683 127.68C57.434 255.363.27 198.197.27 127.683C.27 57.165 57.436 0 127.954 0c70.519 0 127.683 57.165 127.683 127.683Z" fill="#DD4814"></path><path d="M41.133 110.633c-9.419 0-17.05 7.631-17.05 17.05c0 9.414 7.631 17.046 17.05 17.046c9.415 0 17.046-7.632 17.046-17.046c0-9.419-7.631-17.05-17.046-17.05Zm121.715 77.478c-8.153 4.71-10.95 15.13-6.24 23.279c4.705 8.154 15.125 10.949 23.279 6.24c8.153-4.705 10.949-15.125 6.24-23.28c-4.705-8.148-15.131-10.943-23.279-6.239Zm-84.686-60.428c0-16.846 8.368-31.73 21.171-40.742L86.87 66.067c-14.914 9.97-26.012 25.204-30.624 43.047c5.382 4.39 8.826 11.075 8.826 18.568c0 7.489-3.444 14.174-8.826 18.565C60.852 164.094 71.95 179.33 86.87 189.3l12.463-20.88c-12.803-9.007-21.171-23.89-21.171-40.737Zm49.792-49.797c26.013 0 47.355 19.944 49.595 45.38l24.29-.358c-1.194-18.778-9.398-35.636-22.002-48.032c-6.482 2.449-13.97 2.074-20.44-1.656c-6.483-3.741-10.548-10.052-11.659-16.902a74.26 74.26 0 0 0-19.785-2.69a73.787 73.787 0 0 0-32.819 7.663l11.845 21.227a49.596 49.596 0 0 1 20.975-4.632Zm0 99.59a49.601 49.601 0 0 1-20.974-4.632l-11.845 21.225a73.712 73.712 0 0 0 32.82 7.671a74.04 74.04 0 0 0 19.784-2.697c1.111-6.85 5.177-13.155 11.658-16.902c6.476-3.737 13.959-4.105 20.44-1.656c12.605-12.396 20.808-29.254 22.004-48.032l-24.297-.358c-2.235 25.443-23.576 45.38-49.59 45.38Zm34.888-110.231c8.154 4.708 18.575 1.92 23.279-6.234c4.71-8.154 1.92-18.575-6.234-23.285c-8.154-4.704-18.574-1.91-23.285 6.244c-4.703 8.15-1.908 18.57 6.24 23.275Z" fill="#FFF"></path></svg>',
          hFlip: false,
        },
        _type: "icon.manager",
        icon: "logos:ubuntu",
      },
      _type: "icon",
    },
    name: "Ubuntu",
    homepage: "https://ubuntu.com",
    slug: {
      current: "ubuntu",
      _type: "slug",
    },
    vendor: "Canonical",
    _type: "os",
  },
  {
    _id: "ffebb051-7321-4379-aeaa-ef1c726c92b4",
    slug: {
      _type: "slug",
      current: "macos",
    },
    _rev: "7V6W77YnYTSXWZozOSh24B",
    icon: {
      _type: "icon",
      predefined: {
        _type: "icon.manager",
        icon: "mdi:apple",
        metadata: {
          collectionId: "mdi",
          iconName: "apple",
          url: "https://api.iconify.design/mdi:apple.svg?width=20&height=20",
          vFlip: false,
          author: {
            name: "Pictogrammers",
            url: "https://github.com/Templarian/MaterialDesign",
          },
          downloadUrl:
            "https://api.iconify.design/mdi:apple.svg?width=20&height=20&download=1",
          hFlip: false,
          rotate: 0,
          palette: false,
          inlineSvg:
            '<svg viewBox="0 0 24 24" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47c-1.34.03-1.77-.79-3.29-.79c-1.53 0-2 .77-3.27.82c-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51c1.28-.02 2.5.87 3.29.87c.78 0 2.26-1.07 3.81-.91c.65.03 2.47.26 3.64 1.98c-.09.06-2.17 1.28-2.15 3.81c.03 3.02 2.65 4.03 2.68 4.04c-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5c.13 1.17-.34 2.35-1.04 3.19c-.69.85-1.83 1.51-2.95 1.42c-.15-1.15.41-2.35 1.05-3.11Z" fill="currentColor"></path></svg>',
          flip: "",
          collectionName: "Material Design Icons",
          license: {
            name: "Apache 2.0",
            url: "https://github.com/Templarian/MaterialDesign/blob/master/LICENSE",
          },
          size: {
            width: 20,
            height: 20,
          },
        },
      },
    },
    _updatedAt: "2023-10-18T15:19:28Z",
    vendor: "Apple",
    homepage: "https://www.apple.com/macos/",
    description: {
      nl: null,
      en: null,
      id: null,
    },
    _createdAt: "2023-10-05T15:12:50Z",
    _type: "os",
    matchOsName: "macOS",
    name: "macOS",
  },
];
