// This file is generated by scripts/cache-docs.ts, do not edit it manually
import type { SanityRelease } from "../schema.js";

export const releases: SanityRelease[] = [
  {
    oses: [
      {
        _ref: "2495a35b-5efd-49e6-8999-d248d5285125",
        _type: "reference",
        _key: "5c0f332d8fc8",
      },
    ],
    _createdAt: "2023-10-12T15:36:15Z",
    _rev: "4HbZj3khZcB9nAIJRws1cu",
    currentUsage: 27.250799999999998,
    _id: "cac98ea4-1eeb-4d42-b434-471aeba3571c",
    currentVersion: "117",
    versionSource: [
      {
        caniuse_agent: "chrome",
        _type: "versionSource",
        source: "caniuse",
        _key: "e53a89965f33",
      },
    ],
    _type: "release",
    _updatedAt: "2023-10-14T04:48:39Z",
    browser: {
      _type: "reference",
      _ref: "c4aa2b42-df97-48ff-a80a-7c08653965b3",
    },
  },
  {
    versionSource: [
      {
        caniuse_agent: "chrome",
        _type: "versionSource",
        source: "caniuse",
        _key: "c6ae8b62c69e",
      },
    ],
    oses: [
      {
        _type: "reference",
        _key: "1c93fce36ed5",
        _ref: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
      },
    ],
    browser: {
      _ref: "88fe33e4-5b79-43f8-ac01-ed8a4ac68b1b",
      _type: "reference",
    },
    _rev: "JkTQlzv8nKmBN7XeR0F0O9",
    _updatedAt: "2023-10-14T02:45:47Z",
    currentVersion: "117",
    _createdAt: "2023-10-14T02:45:47Z",
    _type: "release",
    currentUsage: 27.250799999999998,
    _id: "f3feab0b-20a2-4397-9458-bf579d5fd7ea",
  },
  {
    _id: "fbc81068-bd70-434f-a3cf-4c6a8b0a5bac",
    oses: [
      {
        _ref: "a569493f-7ef2-414a-9b06-d8bba525dcd8",
        _type: "reference",
        _key: "a61da5b1b6f7",
      },
      {
        _ref: "ffebb051-7321-4379-aeaa-ef1c726c92b4",
        _type: "reference",
        _key: "e72c497ddd44",
      },
      {
        _ref: "efbb0679-8cf1-41f7-85de-6b98b18e637e",
        _type: "reference",
        _key: "684f32cb2fb0",
      },
      {
        _ref: "2495a35b-5efd-49e6-8999-d248d5285125",
        _type: "reference",
        _key: "9d6c833aebed",
      },
    ],
    _createdAt: "2023-10-05T15:07:57Z",
    browser: {
      _ref: "c4aa2b42-df97-48ff-a80a-7c08653965b3",
      _type: "reference",
    },
    currentUsage: 27.250799999999998,
    currentVersion: "117",
    versionSource: [
      {
        caniuse_agent: "chrome",
        _type: "versionSource",
        source: "caniuse",
        _key: "703be10b156e",
      },
    ],
    _rev: "JkTQlzv8nKmBN7XeR0PjKX",
    _type: "release",
    _updatedAt: "2023-10-14T04:48:30Z",
  },
];
