name: automated-automerge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  automated-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print PR information
        run: |
          echo "=== DEBUG: PR Information ==="
          echo "github.actor: ${{ github.actor }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "=== END DEBUG ==="
      
      - name: Debug - Evaluate conditions
        run: |
          echo "=== DEBUG: Condition Evaluation ==="
          echo "Is dependabot: ${{ github.actor == 'dependabot[bot]' }}"
          echo "Is github-actions: ${{ github.actor == 'github-actions[bot]' }}"
          echo "Is browserslist-update branch: ${{ github.head_ref == 'browserslist-update' }}"
          echo "Is chore/update branch: ${{ github.head_ref == 'chore/update' }}"
          echo "Overall condition result: ${{ github.actor == 'dependabot[bot]' || (github.actor == 'github-actions[bot]' && (github.head_ref == 'browserslist-update' || github.head_ref == 'chore/update')) }}"
          echo "=== END DEBUG ==="
      
      - name: Debug - Test exact multiline condition
        run: |
          echo "=== DEBUG: Testing multiline condition ==="
          echo "Multiline condition result: test"
        if: >
          ${{ 
            github.actor == 'dependabot[bot]' || 
            (github.actor == 'github-actions[bot]' && 
             (github.head_ref == 'browserslist-update' || 
              github.head_ref == 'chore/update'))
          }}
      
      - name: Debug - Test single line condition  
        run: |
          echo "=== DEBUG: Testing single line condition ==="
          echo "Single line condition result: test"
        if: ${{ github.actor == 'dependabot[bot]' || (github.actor == 'github-actions[bot]' && (github.head_ref == 'browserslist-update' || github.head_ref == 'chore/update')) }}
      
      - name: Auto-merge PR (with debug logging)
        if: ${{ github.actor == 'dependabot[bot]' || (github.actor == 'github-actions[bot]' && (github.head_ref == 'browserslist-update' || github.head_ref == 'chore/update')) }}
        run: |
          echo "=== EXECUTING AUTO-MERGE ==="
          echo "This PR meets the conditions for auto-merge"
          echo "Executing: gh pr merge --auto --squash \"$PR_URL\""
          gh pr merge --auto --squash "$PR_URL"
          echo "=== AUTO-MERGE ENABLED ==="
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
