name: automated-automerge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  automated-automerge:
    runs-on: ubuntu-latest
    if: >
      ${{ 
        github.actor == 'dependabot[bot]' || 
        (github.actor == 'github-actions[bot]' && 
         (github.head_ref == 'browserslist-update' || 
          github.head_ref == 'chore/update'))
      }}
    steps:
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
